[package]
name = "mailcrab-frontend"
version = "1.10.0"
edition = "2024"
publish = false
license = "Apache-2.0 OR MIT"
repository = "https://github.com/tweedegolf/mailcrab"
description = "Email test server for development, written in Rust"

[dependencies]
base64 = "0.23.0"
futures = "0.3"
gloo-console = "0.4"
gloo-net = "0.7"
gloo-utils = "0.3"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-json-wasm = "1.0"
timeago = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "CssStyleDeclaration",
  "DomTokenList",
  "Element",
  "Event",
  "EventTarget",
  "HtmlElement",
  "HtmlIFrameElement",
  "HtmlInputElement",
  "HtmlLinkElement",
  "InputEvent",
  "MediaQueryList",
  "NodeList",
  "Notification",
  "NotificationOptions",
] }
yew = "0.23"
yew-hooks = "0.6"
