#!/bin/sh

SVR="${SMTP_SERVER:-127.0.0.1}"
PRT="${SMTP_PORT:-1025}"

for EMAIL in "${@}"
do
  swaks \
    --from swaks_injects@script \
    --to mailcrab@${SVR} \
    --server ${SVR}:${PRT} \
    --data @${EMAIL}
done

# l l
