name: "Build and release"

on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build and release"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Cache build assets
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          backend/target/
          frontend/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Configure Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Download trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'

    - name: Build target amd64
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-musl --manifest-path backend/Cargo.toml

    - name: Copy binary
      run: |
        mkdir bin
        cp target/x86_64-unknown-linux-musl/release/mailcrab-backend bin/mailcrab-amd64
      working-directory: ./backend

    - name: Cargo clean
      run: cargo clean
      working-directory: ./backend

    - name: Build target arm64
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target aarch64-unknown-linux-musl --manifest-path backend/Cargo.toml

    - name: Copy binary
      run: |
        cp target/aarch64-unknown-linux-musl/release/mailcrab-backend bin/mailcrab-arm64
      working-directory: ./backend

    - name: Build frontend
      run: trunk build
      working-directory: ./frontend

    - name: Build docker image
      run: docker buildx build --push --platform=linux/amd64,linux/arm64 . -t marlonb/mailcrab:latest -t marlonb/mailcrab:${{github.ref_name}}

    - name: Archive (tar)
      shell: bash
      run: |
        sha256sum -b "mailcrab-amd64-${{github.ref_name}}" > "mailcrab-amd64-${{github.ref_name}}.sha256"
        sha256sum -b "mailcrab-arm64-${{github.ref_name}}" > "mailcrab-amd64-${{github.ref_name}}.arm64"
      working-directory: bin

    - uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/mailcrab-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}