name: Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: rustup toolchain install stable --profile minimal
      - run: rustup component add clippy

      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            frontend/target/
          key: frontend-${{ hashFiles('frontend/Cargo.toml') }}
          restore-keys: frontend-

      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            backend/target/
          key: backend-linux-x86-64-gnu-${{ hashFiles('backend/Cargo.toml') }}
          restore-keys: backend-linux-x86-64-gnu-

      - run: cargo check && cargo clippy && cargo fmt --check
        working-directory: backend

      - run: cargo check --features imap && cargo clippy --features imap
        working-directory: backend

      - name: Functional test
        run: cargo test --features imap -- --nocapture
        shell: bash
        env:
          HTTP_PORT: 26814
          SMTP_PORT: 33543
        working-directory: backend

      - run: cargo check && cargo clippy && cargo fmt --check
        working-directory: frontend
